### ISSUE TITLE
error: spawn enoent

### ISSUE THREAD

**Issue by mmolenaar1** [cognitom/gulp-sketch#16]
"Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)" 

Error with gulp-sketch 0.0.9 in combination with sketch 3

This error shows up with the following pipe: 

.pipe(sketch({ 
export: 'slices', 
formats: 'svg' }
))

**Comment by cognitom** [comment]
`gulp-sketch` only supports latest version of Sketch app.
But still you can try older version via `npm`

If you need more help, freely reopen this issue and provide the information below. Thanks.

- Sketch version 3.?
- `sketchtool` version
- `gulp-sketch` version
- .sketch file
