### ISSUE TITLE
"x" and "y" properties in JSON output

### ISSUE THREAD

**Issue by andremalkine** [cognitom/gulp-sketch#17]
I'm trying to build a gulp task that uses the `outputJSON` export to generate some boilerplate css that will essentially create a graphical object out of each slice. I am using `{ export: 'slices', formats: 'png', ... }` for my options.

All I'm really after is the height/width of each slice (which looks fine) as well as the x and y coordinates. Ideally the x/y coordinates would be relative to the artboard each slice was on, effectively lifting the same values I see for x and y in my properties inspector on the right in sketch. However, the values seem very strange. I haven't taken the time to try and decode how they are arrived at, but suffice to say they don't seem relative to the page origin, artboard origin, or have any relation to the values in the property inspector.

I'm not sure if this can/should be corrected, but maybe if you help me understand how those values are created, I could make more sense of it.

**Comment by cognitom** [comment]
Have you tried `sketchtool` directly?
`gulp-sketch` is just passing the value from/to that. They have a mailing list about `sketchtool`.

**Comment by andremalkine** [comment]
Thanks! I'll check that out.
