### ISSUE TITLE
Add verbose option to show output from sketchtool

### ISSUE THREAD

**Issue by rewiredpictures** [cognitom/gulp-sketch#19]
Hi-

I have a large sketch file that takes some time to export the artboards from. It would be great to have a verbose option on `gulp-sketch` to show the output from the `sketchtool` process as it's running. I am happy to put together a pull request for it, but wanted to see if that was something others were interested in. Something like:

```
if options.verbose
    program.stdout.on 'data', (data) ->
        gutil.log(data.toString())
```

**Comment by cognitom** [comment]
:+1: 
Seems nice!
