### ISSUE TITLE
Possible to specify slices from a specific artboard?

### ISSUE THREAD

**Issue by craigmdennis** [cognitom/gulp-sketch#21]
More of a question than an issue but I can't find much documentation.

Seeing as sketchtool returns JSON for the structure of the file, is it possible to export all slices from one specific artboard?

**Comment by cognitom** [comment]
Hi @craigmdennis, AFIK, we can't :disappointed: 

This is a kind of workaround by `gulp-filter`:

```javascript
var gulp   = require('gulp');
var sketch = require('gulp-sketch');
var filter = require('gulp-filter');

gulp.task('sketch', function(){
  gulp.src('hello.sketch')
    .pipe(sketch({
      export: 'artboards',
      formats: 'png'
    }))
    .pipe(filter('artbord-name.png'))
    .pipe(gulp.dest('./images/'));
})
```

I think it seems not the right place to ask about it. You could join the mailing list below.
dev@sketchplugins.com

**Comment by craigmdennis** [comment]
Thanks for responding. I was hoping you might point me in the right direction. Thanks.

**Comment by cognitom** [comment]
If you find the way, pls let us know ;)
