### ISSUE TITLE
Sketch 3.5 can't gulp.

### ISSUE THREAD

**Issue by luvmex** [cognitom/gulp-sketch#22]
When update the newest Sketch 3.5 then the file can't compile it.

**Comment by ryanmclaughlin** [comment]
:+1:

**Comment by jackkeller** [comment]
Same, apparently the sketchtool is now included inside the app according to [sketchapp.com/tool/](http://www.sketchapp.com/tool/).

So I installed through that route and running `sketchtool notes` it shows update for version 3.5! Hopeful, however as I run my gulp task the icons are not generated still.

I really don't want to go back to how I used to generate icons, I hope this can be figured out soon.

**Comment by ryanmclaughlin** [comment]
@jackkeller Just learned the same thing. I hope @cognitom is around :D

**Comment by cognitom** [comment]
Hi guys, thanks for reporting. At last I got a time to upgrade to v3.5!
I've updated `gulp-sketch` to refer the script bundled with Sketch.app. Pls check it out ;-)

**Comment by ryanmclaughlin** [comment]
> Hi guys, thanks for reporting. At last I got a time to upgrade to v3.5!
> I've updated gulp-sketch to refer the script bundled with Sketch.app. Pls check it out ;-)

:100: Thanks! @cognitom
