### ISSUE TITLE
What about using `sketchjs`?

### ISSUE THREAD

**Issue by iDuuck** [cognitom/gulp-sketch#25]
Hey, just saw that you (@cognitom) contributed to `sketchjs`.
What if this library uses this package?

**Comment by cognitom** [comment]
Sounds cool!
When `sketchjs` supports all the features `gulp-sketch` supports, we'd be happy to move to your library :-)
Maybe `sketchjs ver 1.0` or later?

**Comment by iDuuck** [comment]
Please give me a short roadmap which functions need to be implemented?!

**Comment by cognitom** [comment]
Here's the list of options. (Basically all features `sketchtool` has)
https://github.com/cognitom/gulp-sketch#options

The code is below:
https://github.com/cognitom/gulp-sketch/blob/master/coffee/index.coffee
