### ISSUE TITLE
max artboards exported

### ISSUE THREAD

**Issue by nitrada** [cognitom/gulp-sketch#31]
hey, since I added artboard no. 789 to my Sketch file, the script won't run anymore. is there a maximum number of artboards that can be exported? a sketchtool limitation?

**Comment by cognitom** [comment]
Hi @nitrada. Looks like "a sketchtool limitation" or just a memory issue on your environment.
(I have never tried with such many artboards. So I'm not sure...)

**Comment by nitrada** [comment]
@cognitom it works with sketchtool directly, so I thought it might rather be a problem on this end…

**Comment by cognitom** [comment]
@nitrada can you provide a repo for reproduction?

**Comment by nitrada** [comment]
@cognitom I invited you to the repo and created a "test-sketch-tool" branch. would be great if you could have a look! :)

**Comment by cognitom** [comment]
@nitrada thanks, I've confirmed the issue: there's no output and looks frozen. I'll look into the code later.

**Comment by cognitom** [comment]
@nitrada I've found a solution. It was actually a bug. I'll update `gulp-sketch` soon. Anyway, thanks for reporting!

**Comment by studiostoll** [comment]
@cognitom great! thanks you very much, i'll give it a go and let you know if it works here.

**Comment by studiostoll** [comment]
@cognitom it works. 👍
