### ISSUE TITLE
Doesnt work with Sketch Version 43

### ISSUE THREAD

**Issue by cilurzo** [cognitom/gulp-sketch#32]
Doesnt work with Sketch Version 43

**Comment by cognitom** [comment]
@cilurzo have you tried version 43.1?

It seems that there were some bugs on Sketch 43.

**Comment by cilurzo** [comment]
@cognitom thank you. with this version it works.

**Comment by cognitom** [comment]
Good!

**Comment by wuaiwuai** [comment]
hey @cognitom, could you also publish this latest version to npm? I am also looking for the sketch 43 updates

**Comment by cognitom** [comment]
@wuaiwuai thanks for reminding! I'll publish 1.0.4 soon, but this updates only test code and dependencies.
I think we don't need to update `gulp-sketch` for `43`, or the latest `44`. Doesn't work?

**Comment by cognitom** [comment]
Ok, v1.0.4 is out.
https://www.npmjs.com/package/gulp-sketch
